Use $HOME/.dak.svc.env

diff --git a/dak/svc/registry/genesis/configure b/dak/svc/registry/genesis/configure
--- a/dak/svc/registry/genesis/configure
+++ b/dak/svc/registry/genesis/configure
@@ -1,47 +1,40 @@
 #!/usr/bin/env bash
 
-. $HOME/.dak.svc.env
+. $HOME/.dak.svc.env  
+. $DIDALIK/dak/util/org/lib/util.sh
 
 echo "- starting $0 on $(date)" # {{{1
 SVC_PATH=${npm_config_svc_path:-../svc}
 echo "- SVC_PATH $SVC_PATH, npm_config_port '$npm_config_port'"
-echo "- $#: $@"
 
-exit
+isSubDir $(dirname $SVC_PATH) . && { echo "INVALID SVC_PATH $SVC_PATH: subdir of $PWD" >&2; exit 2; } || echo "- SVC_PATH $SVC_PATH is outside $PWD"
 
-[ $# -ne 2 ] && {
-  printf '\n\t%s\n\n' 'Usage:'
-  echo -e '\t[ rm -rf config; ] npm run i [ --svc <SVC_PATH> ] <VAULT_URL_USER> <VAULT_URL_HOST>'
-  echo -e "\t# <SVC_PATH>: must be outside of $PWD"
-  echo -e '\t# <VAULT_URL_USER>: e.g., didalik_aim'
-  echo -e '\t# <VAULT_URL_HOST>: use nslookup or /etc/hosts, no raw IP; e.g., gc'
-  exit 1
-}
-
-. registry/org/lib/util.sh
-isSubDir $(dirname $SVC_PATH) .
-set -e
-
-mkdir config # {{{1
-echo "export SVC_URL='$(vault_url $1 $2 $SVC_PATH)'" >> config/.env
-echo "export VAULT_URL_USER='$1'" >> config/.env
-echo "export VAULT_URL_HOST='$2'" >> config/.env
-cd config
+mkdir svc # {{{1
+echo "export SVC_URL='$(vault_url $VAULT_URL_USER $VAULT_URL_HOST $SVC_PATH)'" >> svc/.env
+cd svc
 
 keys=() # [OWNER_SK, OWNER_PK, SVC_SK, SVC_PK] {{{2
 for t in 'OWNER' 'SVC'; do
-  for key in "$(../registry/org/bin/run.mjs generate_keypair)"; do keys+=($key); done
+  for key in "$($DIDALIK/dak/util/org/bin/run.mjs generate_keypair)"; do keys+=($key); done
 done
 echo "export SVC_START='wrangler dev dist/index.mjs'" >> ./.env
 echo "export OWNER_SK='${keys[0]}'" >> ./.env
 echo "export OWNER_PK='${keys[1]}'" >> ./.env
 echo "export SVC_SK='${keys[2]}'" >> ./.env
 echo "export SVC_PK='${keys[3]}'" >> ./.env
-echo "export SVC_NAME='vault'" >> ./.env
+echo "export SVC_NAME='$(basename $(dirname $(realpath ..)))'" >> ./.env
 echo "export SVC_PATH='$SVC_PATH'" >> ./.env
 echo "export THIS_SCRIPT='$0'" >> ./.env
 echo "export TIMESTAMP_NOW='$(date)'" >> ./.env
 . ./.env
+
+# }}}2
+
+cd - > /dev/null
+
+echo -e "- exiting $0 on $(date)\n" # {{{1
+
+exit
 
 [ -e ../config-templates/meta.ts ] || { # {{{2
   echo '- configuring KV'
@@ -69,7 +62,3 @@ envsubst < ../config-templates/package.json > package.json
 wrangler dev --port ${npm_config_port:-8787} dist/index.mjs
 
 # }}}2
-cd - > /dev/null
-
-echo -e "- exiting $0 on $(date)\n" # {{{1
-
